package chargingports;

import java.util.Random;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sneha
 */
public class BillPage extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    String OperatorArray[] = new String[] {"JIO","AIRTEL","VI","BSNL"};
    String ModeArray[] = new String[] {"POSTPAID","PREPAID"};
    
    String PhoneNo;
    float Amount;
    String OperatorSel;
    String ModeSel;
    String Coupon = "NIL";
    String WalletID;
     Random rand = new Random();
    
    float getBalance(String WID) {
        float tempAmt = (float)0.0;
         try {
             
            String WalletID = WID;
            
            
            
            String url = "jdbc:h2:~/test";
            Connection C = DriverManager.getConnection(url,"sa","sa");
       
         
            String query = "Select BALANCE from CHARGEWALLET where ID = '"+WalletID+"';";
          
            
            Statement S = C.createStatement(); 
            ResultSet RS = S.executeQuery(query);
            
             while(RS.next()) {
            tempAmt = RS.getFloat("BALANCE");
            
                 System.out.println("BALANCE : " +Float.toString(tempAmt));
                 return tempAmt;
                 
            }
           S.close();
           C.close();
        } catch (SQLException E) {
            System.out.println(E); 
             showMessageDialog(this,"\t\tError Occured","ERROR",JOptionPane.ERROR_MESSAGE);
            
        }  
        System.out.print(tempAmt);
        return tempAmt;
        
    }
    public BillPage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HeaderPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HeaderPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PhoneText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        AmountText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Operator = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Mode = new javax.swing.JComboBox<>();
        ApplyBtn = new javax.swing.JLabel();
        CouponText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        BalanceBtn = new javax.swing.JLabel();
        GenerateBillBtn = new javax.swing.JLabel();
        MakePaymentBtn = new javax.swing.JLabel();
        HomeNav = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose your role");

        HeaderPanel.setBackground(new java.awt.Color(255, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel2.setText("E-Charge");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(471, 471, 471))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );

        HeaderPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Digital India Initiative");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Recharge Done Better");

        javax.swing.GroupLayout HeaderPanel1Layout = new javax.swing.GroupLayout(HeaderPanel1);
        HeaderPanel1.setLayout(HeaderPanel1Layout);
        HeaderPanel1Layout.setHorizontalGroup(
            HeaderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        HeaderPanel1Layout.setVerticalGroup(
            HeaderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(HeaderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Quick recharge");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Wallet ID");

        PhoneText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Amount");

        AmountText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Operator");

        Operator.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Operator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JIO", "AIRTEL", "VI", "BSNL", " " }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Mode");

        Mode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Mode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POSTPAID", "PREPAID", " " }));

        ApplyBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ApplyBtn.setForeground(new java.awt.Color(255, 51, 51));
        ApplyBtn.setText("Apply Coupon");
        ApplyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApplyBtnMouseClicked(evt);
            }
        });

        CouponText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Coupon Code");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Phone Number");

        IDText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        BalanceBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BalanceBtn.setText("Check Balance");
        BalanceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BalanceBtnMouseClicked(evt);
            }
        });

        GenerateBillBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GenerateBillBtn.setText("Generate Bill");
        GenerateBillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenerateBillBtnMouseClicked(evt);
            }
        });

        MakePaymentBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        MakePaymentBtn.setForeground(new java.awt.Color(255, 51, 51));
        MakePaymentBtn.setText("Make Payment");
        MakePaymentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MakePaymentBtnMouseClicked(evt);
            }
        });

        HomeNav.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HomeNav.setForeground(new java.awt.Color(255, 15, 131));
        HomeNav.setText("Go To Home");
        HomeNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeNavMouseClicked(evt);
            }
        });
        HomeNav.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HomeNavKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HeaderPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GenerateBillBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel14)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AmountText, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(PhoneText)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Operator, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CouponText)
                            .addComponent(IDText))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApplyBtn)
                            .addComponent(BalanceBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(MakePaymentBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(155, 155, 155)
                .addComponent(HomeNav)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(HomeNav))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Operator, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(CouponText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApplyBtn))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(BalanceBtn))))
                    .addComponent(Mode, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateBillBtn)
                    .addComponent(MakePaymentBtn))
                .addGap(65, 65, 65)
                .addComponent(HeaderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApplyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApplyBtnMouseClicked
        // TODO add your handling code here:
        Coupon = CouponText.getText().toUpperCase();
        Amount = Float.parseFloat(AmountText.getText());
        if(Coupon.equals("GET20")) {
             showMessageDialog(this,"\t\tCoupon Applied ","Coupon Code Successful",JOptionPane.PLAIN_MESSAGE);
             Amount = (Amount - (float)(Amount*0.20));
             AmountText.setText(Float.toString(Amount));
             AmountText.setEnabled(false);
        }
        else if(Coupon.equals("DEC10")) {
              showMessageDialog(this,"\t\tCoupon Applied ","Coupon Code Successful",JOptionPane.PLAIN_MESSAGE);
              Amount = (Amount - (float)(Amount*0.20));
             AmountText.setText(Float.toString(Amount));
              AmountText.setEnabled(false);
        }
        else if(Coupon.equals("FREE30")) {
              showMessageDialog(this,"\t\tCoupon Applied ","Coupon Code Successful",JOptionPane.PLAIN_MESSAGE);
              Amount = (Amount - (float)(Amount*0.20));
             AmountText.setText(Float.toString(Amount));
              AmountText.setEnabled(false);
        }
        else {
             showMessageDialog(this,"\t\t Wrong Coupon Code. Try Again","Coupon Code Unsuccessful",JOptionPane.ERROR_MESSAGE);
             Amount = (Amount - (float)(Amount*0.20));
             AmountText.setText(Float.toString(Amount));
              AmountText.setEnabled(false);
        }
    }//GEN-LAST:event_ApplyBtnMouseClicked

    private void BalanceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BalanceBtnMouseClicked
        // TODO add your handling code here:
         try {
            WalletID = IDText.getText().toUpperCase();
            
            
            
            String url = "jdbc:h2:~/test";
            Connection C = DriverManager.getConnection(url,"sa","sa");
       
         
            String query = "Select count(*),BALANCE from CHARGEWALLET where ID = '"+WalletID+"';";
          
            
            Statement S = C.createStatement(); 
            ResultSet RS = S.executeQuery(query);
            
            while(RS.next()) {
            Float tempAmt = RS.getFloat("BALANCE");
            String strAmt = tempAmt.toString();
            if(RS.getInt("count(*)") != 0 ) {
                   String Temp = Float.toString(tempAmt);
                    showMessageDialog(this,"\t\tBALANCE  : RS. "+Temp,"Balance Check",JOptionPane.PLAIN_MESSAGE);
                   
                }
            else {
                    showMessageDialog(this,"\t\t Wallet ID Does Not Exist","Balance Load Error (01)",JOptionPane.ERROR_MESSAGE);

            }
            }
           S.close();
           C.close();
        } catch (SQLException E) {
            System.out.println(E); 
             showMessageDialog(this,"\t\tError Occured","ERROR",JOptionPane.ERROR_MESSAGE);
            
        }  
    }//GEN-LAST:event_BalanceBtnMouseClicked

    private void GenerateBillBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerateBillBtnMouseClicked
        // TODO add your handling code here:
        
        PhoneNo = PhoneText.getText();
        int randInt = rand.nextInt(10000);
        String BillNo = "EC"+PhoneNo+Integer.toString(randInt);
        if(CouponText.getText().isEmpty()) {
            Coupon = "NIL";
        }
        else {
            Coupon = CouponText.getText().toUpperCase();
        }
        Amount = Float.parseFloat(AmountText.getText());
        ModeSel = ModeArray[Mode.getSelectedIndex()];
        OperatorSel = OperatorArray[Operator.getSelectedIndex()];
        WalletID = IDText.getText();
        
         try {
            String url = "jdbc:h2:~/test";
            Connection C = DriverManager.getConnection(url,"sa","sa");
             
            
            String query = "INSERT INTO CHARGEBILL VALUES ('"
                    +BillNo+"','"
                    +PhoneNo+"','"
                    +ModeSel+"','"
                    +OperatorSel+"','"
                    +Coupon+"','"
                    +WalletID+"',"
                    +Amount+");";
            System.out.println(query);
      
            Statement S = C.createStatement();
            S.executeUpdate(query);
            
           showMessageDialog(this,"Successfully Updated The Wallet!","ALERT",JOptionPane.INFORMATION_MESSAGE);
           ConfirmPage P = new ConfirmPage(BillNo);
           P.setVisible(true);
           this.dispose();
                    
            C.close();
            S.close();
        } catch (SQLException E) {System.out.println(E);
         showMessageDialog(this,"\t\tError Occured","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GenerateBillBtnMouseClicked

    private void MakePaymentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakePaymentBtnMouseClicked
        // TODO add your handling code here:
         Amount = Float.parseFloat(AmountText.getText());
         WalletID = IDText.getText();
         
          try {
            String url = "jdbc:h2:~/test";
            Connection C = DriverManager.getConnection(url,"sa","sa");
           
             
            if(getBalance(WalletID.toUpperCase()) < Amount) {
                showMessageDialog(this,"\t\tInsufficient Balance","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            else {
            String query = "UPDATE CHARGEWALLET SET BALANCE = BALANCE - "+Amount+"WHERE ID = '"+WalletID+"';";
      
            Statement S = C.createStatement();
            S.executeUpdate(query);
            
           showMessageDialog(this,"Successfully Paid! \n\t\tClick [GENERATE BILL] to Generate Bill\n","ALERT",JOptionPane.INFORMATION_MESSAGE);
                    
            C.close();
            S.close();
            }
        } catch (SQLException E) {System.out.println(E);
         showMessageDialog(this,"\t\tError Occured","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MakePaymentBtnMouseClicked

    private void HomeNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeNavMouseClicked
        // TODO add your handling code here:
        UserHome M = new UserHome();
        M.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_HomeNavMouseClicked

    private void HomeNavKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HomeNavKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeNavKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountText;
    private javax.swing.JLabel ApplyBtn;
    private javax.swing.JLabel BalanceBtn;
    private javax.swing.JTextField CouponText;
    private javax.swing.JLabel GenerateBillBtn;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel HeaderPanel1;
    private javax.swing.JLabel HomeNav;
    private javax.swing.JTextField IDText;
    private javax.swing.JLabel MakePaymentBtn;
    private javax.swing.JComboBox<String> Mode;
    private javax.swing.JComboBox<String> Operator;
    private javax.swing.JTextField PhoneText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
